"""Readable labels for profile bindings, without executing their actions."""

from __future__ import annotations


def key_label(code: str) -> str:
    names = {
        "KEY_LEFTCTRL": "L Ctrl", "KEY_RIGHTCTRL": "R Ctrl",
        "KEY_LEFTSHIFT": "L Shift", "KEY_RIGHTSHIFT": "R Shift",
        "KEY_LEFTALT": "L Alt", "KEY_RIGHTALT": "R Alt",
        "KEY_LEFTMETA": "L Super", "KEY_RIGHTMETA": "R Super",
        "BTN_LEFT": "Mouse 1", "BTN_RIGHT": "Mouse 2",
        "BTN_MIDDLE": "Mouse 3", "BTN_SIDE": "Mouse 4", "BTN_EXTRA": "Mouse 5",
        "KEY_PAGEUP": "PgUp", "KEY_PAGEDOWN": "PgDn",
        "KEY_BACKSPACE": "Bksp", "KEY_CAPSLOCK": "Caps",
    }
    return names.get(code, code.removeprefix("KEY_").removeprefix("BTN_").replace("_", " ").title())


def mapping_label(profile: dict, control: str) -> str:
    if not profile:
        return "Not loaded"
    if control.startswith("STICK_") and profile.get("stick_mode") == "mouse":
        return "Pointer"
    events = profile.get("macros", {}).get(control)
    if events:
        # Only display a chord for the exact zero-delay press/reverse-release
        # shape generated by the shortcut editor. Timed sequences stay macros.
        downs = [event["code"] for event in events if event["down"]]
        expected = [
            *({"code": code, "down": True, "delay_ms": 0} for code in downs),
            *({"code": code, "down": False, "delay_ms": 0} for code in reversed(downs)),
        ]
        if len(downs) > 1 and len(set(downs)) == len(downs) and events == expected:
            return " + ".join(key_label(code) for code in downs)
        return f"Macro ({len(events)})"
    code = profile.get("bindings", {}).get(control)
    return key_label(code) if code else "Unassigned"
